### ISSUE TITLE
compilation failed of R 4.0.2

### ISSUE THREAD

**Issue by zxy1555847** [JiaxiangBU/tutoring2#59] opened 2020-07-15 09:33 UTC
我目前在服务器上使用R，这个R是由conda安装。我按照
if (!require("devtools")) install.packages("devtools")
devtools::install_github("thierrygosselin/radiator")
library(radiator)
的方法去安装radiator，执行第一条代码就报错compilation failed。

然后我想先在自己的电脑（windows，R版本4.0.2）上试着安装一下，
devtools可以正常安装，但是第二条代码devtools::install_github("thierrygosselin/radiator")，需要rtools，我又装了rtools4.0，然后报没有rlang包的错，我利用install.packages("rlang")命令装rlang，报了compilation failed的错。
 

<!-- ### 简述问题
 也就是目前的linux系统下，conda装的R4.0.2报compilation failed，
我自己的电脑，也是报错如此。
我刚接触利用R分析我的数据，主要是想用radiator这个包，也就是我之前没有对我的R进行任何配置，我也不熟悉R，这个问题已经是我能力之外了！所以请求帮助！！

<!-- ### 希望输出的结果
希望，我有生之年可以安装好radiator。

服务器报错：
ERROR: compilation failed for package ‘roxygen2’
* removing ‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/roxygen2                                      ’
ERROR: dependency ‘later’ is not available for package ‘promises’
* removing ‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/promises                                      ’
ERROR: dependency ‘fs’ is not available for package ‘usethis’
* removing ‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/usethis’
ERROR: dependency ‘promises’ is not available for package ‘DT’
* removing ‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/DT’
ERROR: dependencies ‘usethis’, ‘DT’, ‘roxygen2’ are not available for package ‘d                                      evtools’
* removing ‘/home/mee/public/yaotianyi/conda/condabiosoft/lib/R/library/devtools                                      ’

The downloaded source packages are in
        ‘/tmp/RtmpSY5M5z/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("devtools") :
  installation of package ‘later’ had non-zero exit status
2: In install.packages("devtools") :
  installation of package ‘fs’ had non-zero exit status
3: In install.packages("devtools") :
  installation of package ‘roxygen2’ had non-zero exit status
4: In install.packages("devtools") :
  installation of package ‘promises’ had non-zero exit status
5: In install.packages("devtools") :
  installation of package ‘usethis’ had non-zero exit status
6: In install.packages("devtools") :
  installation of package ‘DT’ had non-zero exit status
7: In install.packages("devtools") :
  installation of package ‘devtools’ had non-zero exit status
>

自己电脑报错：
install.packages("rlang")

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.4.6  0.4.7              TRUE

installing the source package ‘rlang’

trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.4.7.tar.gz'
Content type 'application/x-gzip' length 847308 bytes (827 KB)
downloaded 827 KB

* installing *source* package 'rlang' ...
** 成功将'rlang'程序包解包并MD5和检查
** using staged installation
** libs

*** arch - i386
"c:/rtools40/mingw32/bin/"gcc  -I"D:/PROGRA~2/R-40~1.2/include" -DNDEBUG -I./lib/         -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c capture.c -o capture.o
sh: c:/rtools40/mingw32/bin/gcc: No such file or directory
make: *** [D:/PROGRA~2/R-40~1.2/etc/i386/Makeconf:222: capture.o] Error 127
ERROR: compilation failed for package 'rlang'
* removing 'D:/Program Files (x86)/R-4.0.2/library/rlang'
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\MACHENIKE\AppData\Local\Temp\RtmpMjEdNG\downloaded_packages’
>

**Comment by JiaxiangBU** [comment] 2020-07-23 08:45
Duplicate of #57

**Closed as completed by JiaxiangBU** 2020-07-23 08:45 UTC
